export const iconOptions = [
  { title: "Accesorios (gema)", value: "accesorios" },
  { title: "Carteras (bolsa)", value: "carteras" },
  { title: "Perfumes (spray)", value: "perfumes" },
  { title: "Piercings (círculo)", value: "piercings" },
  { title: "Maquillaje (pincel)", value: "maquillaje" },
  { title: "Lentes", value: "lentes" },
  { title: "Gorros (corona)", value: "gorros" },
  { title: "Y mucho más (+)", value: "mas" },
  { title: "Ropa (remera)", value: "ropa" },
  { title: "Calzado", value: "calzado" },
  { title: "Relojes", value: "relojes" },
  { title: "Regalos", value: "regalos" },
  { title: "Corazón", value: "corazon" },
  { title: "Brillos", value: "brillos" },
  { title: "Flores", value: "flores" },
  { title: "Estrella", value: "estrella" },
  { title: "Tijera (peluquería)", value: "tijera" },
  { title: "Música", value: "musica" },
  { title: "Celulares", value: "celulares" },
  { title: "Hogar", value: "hogar" },
  { title: "Paleta de colores", value: "paleta" },
  { title: "Moños", value: "monos" },
  { title: "Bebés", value: "bebes" },
  { title: "Cámara", value: "camara" },
  { title: "Paraguas", value: "paraguas" },
  { title: "Mochilas", value: "mochilas" },
  { title: "Golosinas", value: "golosinas" },
  { title: "Stickers", value: "stickers" },
  { title: "Mascotas", value: "mascotas" },
] as const;

export type IconKey = (typeof iconOptions)[number]["value"];
